# -*- coding: utf-8 -*-
"""Mall_Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14__zf4d1zFVk4EvWAcVI1eUmz2ow5HIb

# Mall Customer Segmentation Using K-Means Clustering

This project applies **K-Means clustering** to the Mall Customers dataset from Kaggle, aiming to segment customers based on behavior.  
We’ll use annual income and spending score to discover hidden customer patterns and visualize them using clustering techniques.

**Objectives:**
- Perform data preprocessing.
- Determine optimal number of clusters (Elbow Method).
- Apply K-Means clustering.
- Visualize the customer segments.

Importing necessary Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

""" Loading Data while Handling Error"""

def load_file():
    try:
        df = pd.read_csv("Mall_Customers.csv")
        print(" File loaded successfully!")
        return df
    except FileNotFoundError:
        print("File not found. Make sure it is in the current directory.")
        return None
    except Exception as e:
        print(f"Error: {str(e)}")
        return None

df = load_file()

"""Getting information about datasets and checking null and duplicate values"""

print(df.head())
print(df.info())
print("\nMissing Values:\n", df.isnull().sum())
print("\nDuplicates:", df.duplicated().sum())

"""Findings:

-There are total 200 rows with 5 columns (4 intype and 1 object type column)

-There is no duplicates and null values in the datasets.

Dropping unnecessary column
"""

df = df.drop('CustomerID', axis=1)

"""Feature Selection"""

X = df[['Annual Income (k$)', 'Spending Score (1-100)']]

"""Feature Scaling"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""Elbow Method to Find Optimal Clusters"""

wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(8, 6))
plt.plot(range(1, 11), wcss, marker='o')
plt.title('Elbow Method for Optimal k')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

"""Applying K-Means

"""

kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
df['Cluster'] = kmeans.fit_predict(X_scaled)

"""Visualizing Clusters"""

plt.figure(figsize=(10, 6))
sns.scatterplot(
    x='Annual Income (k$)',
    y='Spending Score (1-100)',
    hue='Cluster',
    data=df,
    palette='Set2',
    s=100
)
plt.title('Customer Segmentation using K-Means (2D)')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend(title='Cluster')
plt.grid(True)
plt.show()

cluster_counts = df['Cluster'].value_counts()
print("Number of customers in each cluster:",cluster_counts)
cluster_averages = df.groupby('Cluster')[['Annual Income (k$)', 'Spending Score (1-100)']].mean()
print("Average Income and Spending Score per Cluster:")
print(cluster_averages)

"""Customer Segemntation Interpretation
The clustering results from K-Means (k=5) reveal five distinct groups of mall customers based on their annual income and spending score. These segments highlight differences in consumer behavior.

-Cluster 0

Customers: 81

Traits: Moderate income, moderate spending

Findings: Practical, budget-aware shoppers who spend within their means. They may be influenced by offers that provide value for money.

-Cluster 1

Customers: 39

Traits: High income, high spending

Findings: The most profitable group. These customers are likely brand-conscious and value quality. Loyalty programs and premium services may retain them.

-Cluster 2

Customers: 22

Traits: Low income, high spending

Findings: Impulse buyers or experience-seekers. Despite limited income, they are active spenders. Marketing should focus on perceived value and satisfaction.

-Cluster 3

Customers: 35

Findings: High income, low spending

Findings: Wealthy but reserved spenders. This group may need more trust or personalization before making purchases. Exclusive or status-based marketing could help.

-Cluster 4

Customers: 23

Traits: Low income, low spending

Findings: Price-sensitive and cautious. Not the main target for premium products, but could be approached with entry-level or budget-friendly deals.
"""